name: Linux tests

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*.yml'
      - 'requirements/*.txt'
      - 'Makefile'
      - 'MANIFEST.in'
      - '**.bat'
      - '**.py'
      - '**.sh'

  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/*.yml'
      - 'requirements/*.txt'
      - 'MANIFEST.in'
      - '**.bat'
      - '**.py'
      - '**.sh'

jobs:
  ############################################################################
  # Close previous builds on the same branch
  ############################################################################
  cleanup-previous-runs:
    name: Cleanup previous builds
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_EVENT_NAME
      - uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  ############################################################################
  # Python tests
  ############################################################################
  linux-py:
    name: Linux py${{ matrix.PYTHON_VERSION }} tests
    runs-on: ubuntu-latest
    needs: cleanup-previous-runs
    env:
      CI: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.6', '3.7', '3.8']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py-${{ matrix.PYTHON_VERSION }}-pip-${{ hashFiles('**/setup.py') }}
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade check-manifest codecov pip pre-commit setuptools
          python -m pip install --editable .
      - name: Show python environment
        run: |
          python --version
          python -m pip list
      - name: Run pre-commit checks
        run: |
          pre-commit run -a
